<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentResults"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    <PackageReference Include="System.Reactive"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SemiPlot.Tests"/>
  </ItemGroup>

</Project>
