<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentResults"/>
    <PackageReference Include="System.Reactive"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SemiPlot.Tests.Unit"/>
    <InternalsVisibleTo Include="SemiPlot.Tests.Integration"/>
  </ItemGroup>

</Project>
