<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!-- Program.Main is the explicit entry point. -->
    <StartupObject>SemiPlot.UI.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SemiPlot.Tests.Unit"/>
    <InternalsVisibleTo Include="SemiPlot.Tests.Integration"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"/>
    <PackageReference Include="Avalonia.Desktop"/>
    <PackageReference Include="Avalonia.HarfBuzz"/>
    <PackageReference Include="Avalonia.Themes.Fluent"/>
    <PackageReference Include="Avalonia.Win32"/>
    <PackageReference Include="Avalonia.Skia"/>
    <PackageReference Include="ReactiveUI.Avalonia"/>
    <PackageReference Include="ScottPlot.Avalonia"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    <PackageReference Include="Microsoft.Extensions.Logging"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="Serilog.Sinks.Console"/>
    <PackageReference Include="Serilog.Sinks.File"/>
    <PackageReference Include="System.Reactive"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemiPlot.Core\SemiPlot.Core.csproj"/>
    <ProjectReference Include="..\SemiPlot.DataSource.Postgres\SemiPlot.DataSource.Postgres.csproj"/>
  </ItemGroup>

</Project>
