<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql"/>
    <PackageReference Include="System.CommandLine"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemiPlot.Core\SemiPlot.Core.csproj"/>
  </ItemGroup>

</Project>
